# GitHub Issue template chooser for Ummah.build Ideas
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

blank_issues_enabled: false
contact_links:
  - name: Ummah.build
    url: https://ummah.build
    about: Main ummah.build site
